const KEY="basiraHadith.v1";let db=loadDB();
function loadDB(){try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return{sources:Array.isArray(x.sources)?x.sources:[],hadiths:Array.isArray(x.hadiths)?x.hadiths:[],settings:x.settings||{theme:"light"}}}catch{return{sources:[],hadiths:[],settings:{theme:"light"}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function id(prefix){return prefix+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,7)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function statusBadge(s){const c=s==="منشور"?"published":s==="موثق"?"verified":s==="مراجعة"?"review":"draft";return '<span class="badge '+c+'">'+esc(s)+'</span>'}
function show(view){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("hidden",x.id!==view));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.view===view));renderAll();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.view)));
document.getElementById("sourceForm").addEventListener("submit",e=>{e.preventDefault();const file=document.getElementById("sFile").files[0];const s={id:id("src"),book:sBook.value.trim(),author:sAuthor.value.trim(),type:sType.value,editor:sEditor.value.trim(),edition:sEdition.value.trim(),publisher:sPublisher.value.trim(),year:sYear.value.trim(),isbn:sIsbn.value.trim(),file:file?file.name:"",notes:sNotes.value.trim(),createdAt:new Date().toISOString()};if(!s.book)return;db.sources.unshift(s);save();e.target.reset();message("sourceMsg","تم حفظ المصدر في السجل المحلي. يمكنك الآن إضافة الأحاديث المرتبطة به.");});
document.getElementById("hadithForm").addEventListener("submit",e=>{e.preventDefault();const source=hSource.value;const h={id:id("had"),sourceId:source,number:hNumber.value.trim(),chapter:hChapter.value.trim(),narrator:hNarrator.value.trim(),text:hText.value.trim(),isnad:hIsnad.value.trim(),matn:hMatn.value.trim(),page:hPage.value.trim(),keywords:hKeywords.value.trim(),notes:hNotes.value.trim(),status:"مراجعة",createdAt:new Date().toISOString(),review:{}};if(!source||!h.text){message("hadithMsg","اختر مصدرًا وأدخل النص الأصلي للحديث.");return}db.hadiths.unshift(h);save();e.target.reset();message("hadithMsg","تم حفظ السجل وإحالته إلى المراجعة العلمية.");});
function message(el,text){const x=document.getElementById(el);x.textContent=text;x.classList.remove("hidden");setTimeout(()=>x.classList.add("hidden"),3500)}
function renderAll(){renderMetrics();renderSourceOptions();renderSources();renderHadiths();renderReview();renderRecent();renderCatalog()}
function renderMetrics(){mSources.textContent=db.sources.length;mHadiths.textContent=db.hadiths.length;mReview.textContent=db.hadiths.filter(x=>x.status==="مراجعة").length;mPublished.textContent=db.hadiths.filter(x=>x.status==="منشور").length}
function renderSourceOptions(){const val=hSource.value;hSource.innerHTML='<option value="">اختر المصدر *</option>'+db.sources.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.book)+(s.author?" — "+esc(s.author):"")+"</option>").join("");if(db.sources.some(s=>s.id===val))hSource.value=val}
function renderRecent(){recentSources.innerHTML=db.sources.slice(0,8).map(s=>{const n=db.hadiths.filter(h=>h.sourceId===s.id).length;return '<tr><td>'+esc(s.book)+'</td><td>'+esc(s.author||"—")+'</td><td>'+statusBadge(n?"يحتوي سجلات":"مصدر")+'</td><td>'+n+"</td></tr>"}).join("")||'<tr><td colspan="4">لا توجد مصادر بعد.</td></tr>'}
function renderSources(){const q=(sourceSearch.value||"").toLowerCase();sourcesRows.innerHTML=db.sources.filter(s=>(s.book+" "+s.author+" "+s.editor).toLowerCase().includes(q)).map(s=>{const n=db.hadiths.filter(h=>h.sourceId===s.id).length;return '<tr><td><b>'+esc(s.book)+'</b><div class="mini">'+esc(s.file||"لا يوجد ملف")+'</div></td><td>'+esc(s.author||"—")+'</td><td>'+esc(s.type)+'</td><td>المحقق: '+esc(s.editor||"—")+'<br>الناشر: '+esc(s.publisher||"—")+'<br>الطبعة: '+esc(s.edition||"—")+' '+esc(s.year||"")+'</td><td>'+n+'</td><td><button onclick="removeSource(\''+s.id+'\')">حذف</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد مصادر مطابقة.</td></tr>'}
function renderHadiths(){const q=(hadithSearch.value||"").toLowerCase(),st=hadithStatus.value;hadithRows.innerHTML=db.hadiths.filter(h=>{const s=db.sources.find(x=>x.id===h.sourceId);return (!st||h.status===st)&&((h.text+" "+h.narrator+" "+(s?.book||"")+" "+h.number).toLowerCase().includes(q))}).map(h=>{const s=db.sources.find(x=>x.id===h.sourceId);return '<tr><td>'+esc(h.number||"—")+'</td><td>'+esc(s?.book||"مصدر محذوف")+'</td><td class="truncate" title="'+esc(h.text)+'">'+esc(h.text)+'</td><td>'+esc(h.narrator||"—")+'</td><td>'+statusBadge(h.status)+'</td><td><button onclick="advanceHadith(\''+h.id+'\')">المرحلة التالية</button> <button onclick="removeHadith(\''+h.id+'\')">حذف</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد سجلات مطابقة.</td></tr>'}
function renderReview(){reviewRows.innerHTML=db.hadiths.filter(h=>h.status!=="منشور").map(h=>{const s=db.sources.find(x=>x.id===h.sourceId);return '<tr><td>'+esc(h.id)+'</td><td>'+esc(s?.book||"مصدر محذوف")+'</td><td class="truncate">'+esc(h.text)+'</td><td>'+statusBadge(h.status)+'</td><td><button onclick="advanceHadith(\''+h.id+'\')">اعتماد المرحلة التالية</button></td></tr>'}).join("")||'<tr><td colspan="5">لا توجد سجلات تحتاج مراجعة.</td></tr>'}
function renderCatalog(){const q=(catalogSearch.value||"").toLowerCase();const items=db.sources.filter(s=>(s.book+" "+s.author).toLowerCase().includes(q));const cards=[];items.forEach(s=>{const hs=db.hadiths.filter(h=>h.sourceId===s.id);cards.push('<article class="catalog-card"><h3>📚 '+esc(s.book)+'</h3><p>المؤلف: '+esc(s.author||"غير مدخل")+'</p><p>النوع: '+esc(s.type)+' · الأحاديث المسجلة: '+hs.length+'</p><p>المحقق: '+esc(s.editor||"غير مدخل")+' · الناشر: '+esc(s.publisher||"غير مدخل")+'</p></article>')});catalogResults.innerHTML=cards.join("")||'<div class="notice">لا توجد نتائج.</div>'}
function advanceHadith(hid){const h=db.hadiths.find(x=>x.id===hid);if(!h)return;h.status=h.status==="مراجعة"?"موثق":h.status==="موثق"?"منشور":"منشور";h.review.lastTransitionAt=new Date().toISOString();save()}
function removeSource(sid){if(!confirm("حذف المصدر؟ ستبقى الأحاديث المرتبطة به لكنها ستظهر بلا مصدر."))return;db.sources=db.sources.filter(s=>s.id!==sid);save()}
function removeHadith(hid){if(!confirm("حذف هذا السجل؟"))return;db.hadiths=db.hadiths.filter(h=>h.id!==hid);save()}
function exportDB(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),...db},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="basira-hadith-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
exportBtn.addEventListener("click",exportDB);quickExport.addEventListener("click",exportDB);
themeBtn.addEventListener("click",()=>{db.settings.theme=db.settings.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=db.settings.theme;save()});
function applyTheme(){document.documentElement.dataset.theme=db.settings.theme==="dark"?"dark":""}
sourceSearch.addEventListener("input",renderSources);hadithSearch.addEventListener("input",renderHadiths);hadithStatus.addEventListener("change",renderHadiths);catalogSearch.addEventListener("input",renderCatalog);
clearSources.addEventListener("click",()=>{if(confirm("سيتم حذف جميع المصادر والأحاديث من هذا المتصفح. استخدم التصدير أولًا إن كانت البيانات مهمة.")){db.sources=[];db.hadiths=[];save()}});
applyTheme();renderAll();