const KEY="basiraHadith.v2";let db=load();function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return{sources:x.sources||[],hadiths:x.hadiths||[],settings:x.settings||{theme:"light"}}}catch{return{sources:[],hadiths:[],settings:{theme:"light"}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}function uid(p){return p+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,7)}function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function badge(s){const c=s==="منشور"?"published":s==="موثق"?"verified":s==="مراجعة"?"review":"draft";return '<span class="badge '+c+'">'+esc(s)+'</span>'}
function go(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("hidden",x.id!==v));document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));renderAll();scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-view]").forEach(x=>x.addEventListener("click",()=>go(x.dataset.view)));
function msg(id,t){const x=document.getElementById(id);x.textContent=t;x.classList.remove("hidden");setTimeout(()=>x.classList.add("hidden"),3500)}
sourceForm.addEventListener("submit",e=>{e.preventDefault();const f=sFile.files[0],s={id:uid("src"),book:sBook.value.trim(),author:sAuthor.value.trim(),type:sType.value,editor:sEditor.value.trim(),edition:sEdition.value.trim(),publisher:sPublisher.value.trim(),year:sYear.value.trim(),isbn:sIsbn.value.trim(),url:sUrl.value.trim(),file:f?.name||"",notes:sNotes.value.trim(),createdAt:new Date().toISOString()};if(!s.book)return;db.sources.unshift(s);save();e.target.reset();msg("sourceMsg","تم حفظ المصدر. يمكنك الآن ربط الأحاديث به.")});
hadithForm.addEventListener("submit",e=>{e.preventDefault();const h={id:uid("had"),sourceId:hSource.value,number:hNumber.value.trim(),chapter:hChapter.value.trim(),narrator:hNarrator.value.trim(),text:hText.value.trim(),isnad:hIsnad.value.trim(),matn:hMatn.value.trim(),page:hPage.value.trim(),keywords:hKeywords.value.trim(),reference:hReference.value.trim(),notes:hNotes.value.trim(),status:"مراجعة",createdAt:new Date().toISOString(),history:[{status:"مراجعة",at:new Date().toISOString()}]};if(!h.sourceId||!h.text){msg("hadithMsg","اختر المصدر وأدخل النص الأصلي.");return}db.hadiths.unshift(h);save();e.target.reset();msg("hadithMsg","حُفظ السجل وأُحيل إلى المراجعة العلمية.")});
function renderAll(){mSources.textContent=db.sources.length;mHadiths.textContent=db.hadiths.length;mReview.textContent=db.hadiths.filter(h=>h.status==="مراجعة").length;mPublished.textContent=db.hadiths.filter(h=>h.status!=="مراجعة").length;renderOptions();renderSources();renderHadiths();renderReview();renderRecent();renderStats();renderCatalog()}
function renderOptions(){const v=hSource.value;hSource.innerHTML='<option value="">اختر المصدر *</option>'+db.sources.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.book)+(s.author?" — "+esc(s.author):"")+"</option>").join("");if(db.sources.some(s=>s.id===v))hSource.value=v}
function renderRecent(){recentSources.innerHTML=db.sources.slice(0,7).map(s=>{const n=db.hadiths.filter(h=>h.sourceId===s.id).length;return '<tr><td><b>'+esc(s.book)+'</b></td><td>'+esc(s.author||"—")+'</td><td>'+n+'</td><td>'+badge(n?"مصدر نشط":"مصدر")+'</td></tr>'}).join("")||'<tr><td colspan="4">لا توجد مصادر.</td></tr>'}
function renderSources(){const q=(sourceSearch.value||"").toLowerCase();sourcesRows.innerHTML=db.sources.filter(s=>(s.book+" "+s.author+" "+s.editor+" "+s.publisher).toLowerCase().includes(q)).map(s=>{const n=db.hadiths.filter(h=>h.sourceId===s.id).length;return '<tr><td><b>'+esc(s.book)+'</b><div class="mini">'+esc(s.file||"لا يوجد ملف")+'</div></td><td>'+esc(s.author||"—")+'</td><td>'+esc(s.type)+'</td><td>المحقق: '+esc(s.editor||"—")+'<br>الناشر: '+esc(s.publisher||"—")+'<br>'+esc(s.edition||"")+' '+esc(s.year||"")+'</td><td>'+n+'</td><td><button class="mini-action" onclick="sourceView(\''+s.id+'\')">عرض</button> <button class="mini-action" onclick="removeSource(\''+s.id+'\')">حذف</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد نتائج.</td></tr>'}
function renderHadiths(){const q=(hadithSearch.value||"").toLowerCase(),st=hadithStatus.value;hadithRows.innerHTML=db.hadiths.filter(h=>{const s=db.sources.find(x=>x.id===h.sourceId);return(!st||h.status===st)&&((h.text+" "+h.narrator+" "+(s?.book||"")+" "+h.number+" "+h.keywords).toLowerCase().includes(q))}).map(h=>{const s=db.sources.find(x=>x.id===h.sourceId);return '<tr><td>'+esc(h.number||"—")+'</td><td>'+esc(s?.book||"مصدر غير معروف")+'</td><td class="truncate" title="'+esc(h.text)+'">'+esc(h.text)+'</td><td>'+esc(h.narrator||"—")+'</td><td>'+badge(h.status)+'</td><td><button class="mini-action" onclick="hadithView(\''+h.id+'\')">فتح</button> <button class="mini-action" onclick="advance(\''+h.id+'\')">التالي</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد سجلات.</td></tr>'}
function renderReview(){reviewRows.innerHTML=db.hadiths.map(h=>{const s=db.sources.find(x=>x.id===h.sourceId);const last=h.history?.at(-1);return '<tr><td>'+esc(h.id)+'</td><td>'+esc(s?.book||"—")+'</td><td class="truncate">'+esc(h.text)+'</td><td>'+badge(h.status)+'</td><td>'+esc(last?.at?new Date(last.at).toLocaleString("ar-LY"):"—")+'</td><td><button class="mini-action" onclick="hadithView(\''+h.id+'\')">مراجعة</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد سجلات.</td></tr>'}
function renderStats(){const total=db.hadiths.length||1,states=[["مراجعة",db.hadiths.filter(h=>h.status==="مراجعة").length],["موثق",db.hadiths.filter(h=>h.status==="موثق").length],["منشور",db.hadiths.filter(h=>h.status==="منشور").length]];statusStats.innerHTML=states.map(x=>'<div class="bar-row"><div class="bar-label"><span>'+x[0]+'</span><b>'+x[1]+'</b></div><div class="bar"><i style="width:'+Math.round(x[1]/total*100)+'%"></i></div></div>').join("");const types={};db.sources.forEach(s=>types[s.type]=(types[s.type]||0)+1);const mx=Math.max(1,...Object.values(types));typeStats.innerHTML=Object.entries(types).map(x=>'<div class="bar-row"><div class="bar-label"><span>'+esc(x[0])+'</span><b>'+x[1]+'</b></div><div class="bar"><i style="width:'+Math.round(x[1]/mx*100)+'%"></i></div></div>').join("")||'<p class="muted">لا توجد مصادر.</p>'}
function renderCatalog(){const q=(catalogSearch.value||"").toLowerCase();catalogResults.innerHTML=db.sources.filter(s=>(s.book+" "+s.author).toLowerCase().includes(q)).map(s=>{const hs=db.hadiths.filter(h=>h.sourceId===s.id);return '<article class="catalog-card"><h3>📚 '+esc(s.book)+'</h3><p>المؤلف: '+esc(s.author||"غير مدخل")+'</p><p>النوع: '+esc(s.type)+' · السجلات: '+hs.length+'</p><p>المحقق: '+esc(s.editor||"—")+' · '+esc(s.publisher||"—")+'</p><button class="mini-action" onclick="sourceView(\''+s.id+'\')">تفاصيل المصدر</button></article>'}).join("")||'<div class="notice">لا توجد نتائج.</div>'}
function sourceView(id){const s=db.sources.find(x=>x.id===id);if(!s)return;const hs=db.hadiths.filter(h=>h.sourceId===id);openModal('<h2>📚 '+esc(s.book)+'</h2><p><b>المؤلف:</b> '+esc(s.author||"—")+'</p><p><b>المحقق:</b> '+esc(s.editor||"—")+'</p><p><b>الطبعة:</b> '+esc(s.edition||"—")+' · <b>الناشر:</b> '+esc(s.publisher||"—")+' · <b>السنة:</b> '+esc(s.year||"—")+'</p><p><b>السجلات المرتبطة:</b> '+hs.length+'</p><p>'+esc(s.notes||"")+'</p>')}
function hadithView(id){const h=db.hadiths.find(x=>x.id===id);if(!h)return;const s=db.sources.find(x=>x.id===h.sourceId);openModal('<h2>📜 الحديث '+esc(h.number||"")+'</h2><p><b>المصدر:</b> '+esc(s?.book||"—")+' · <b>الباب:</b> '+esc(h.chapter||"—")+'</p><div class="quote">'+esc(h.text)+'</div><h3>الإسناد</h3><p>'+esc(h.isnad||"لم يُفصل بعد.")+'</p><h3>المتن</h3><p>'+esc(h.matn||"لم يُفصل بعد.")+'</p><p><b>الراوي:</b> '+esc(h.narrator||"—")+' · <b>الموضع:</b> '+esc(h.page||"—")+'</p><p><b>الكلمات المفتاحية:</b> '+esc(h.keywords||"—")+'</p><div class="notice"><b>الحالة:</b> '+badge(h.status)+'</div><div class="form-actions" style="margin-top:12px"><button class="primary" onclick="advance(\''+h.id+'\');closeModal()">اعتماد المرحلة التالية</button><button onclick="window.print()">طباعة</button></div>')}
function advance(id){const h=db.hadiths.find(x=>x.id===id);if(!h)return;h.status=h.status==="مراجعة"?"موثق":h.status==="موثق"?"منشور":"منشور";h.history=h.history||[];h.history.push({status:h.status,at:new Date().toISOString()});save()}
function removeSource(id){if(!confirm("حذف المصدر؟ ستبقى الأحاديث مع فقدان رابط المصدر."))return;db.sources=db.sources.filter(x=>x.id!==id);save()}
function exportDB(){const payload={schema:"basira-hadith",version:"1.5",exportedAt:new Date().toISOString(),...db};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download="basira-hadith-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function openModal(html){modalBody.innerHTML=html;modal.classList.remove("hidden")}function closeModal(){modal.classList.add("hidden")}modalClose.onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()}
exportBtn.onclick=exportDB;quickExport.onclick=exportDB;sourceSearch.oninput=renderSources;hadithSearch.oninput=renderHadiths;hadithStatus.onchange=renderHadiths;catalogSearch.oninput=renderCatalog;
clearSources.onclick=()=>{if(confirm("سيتم حذف جميع المصادر والأحاديث المحلية. صدّر نسخة احتياطية أولًا.")){db.sources=[];db.hadiths=[];save()}}
themeBtn.onclick=()=>{db.settings.theme=db.settings.theme==="dark"?"light":"dark";applyTheme();save()};function applyTheme(){document.documentElement.dataset.theme=db.settings.theme==="dark"?"dark":""}applyTheme();renderAll();