const sourceForm=document.getElementById("sourceForm");const sFile=document.getElementById("sFile");const sBook=document.getElementById("sBook");const sAuthor=document.getElementById("sAuthor");const sType=document.getElementById("sType");const sEditor=document.getElementById("sEditor");const sEdition=document.getElementById("sEdition");const sPublisher=document.getElementById("sPublisher");const sYear=document.getElementById("sYear");const sIsbn=document.getElementById("sIsbn");const sUrl=document.getElementById("sUrl");const sNotes=document.getElementById("sNotes");const sourceMsg=document.getElementById("sourceMsg");const hadithForm=document.getElementById("hadithForm");const hSource=document.getElementById("hSource");const hNumber=document.getElementById("hNumber");const hChapter=document.getElementById("hChapter");const hNarrator=document.getElementById("hNarrator");const hText=document.getElementById("hText");const hIsnad=document.getElementById("hIsnad");const hMatn=document.getElementById("hMatn");const hPage=document.getElementById("hPage");const hKeywords=document.getElementById("hKeywords");const hReference=document.getElementById("hReference");const hNotes=document.getElementById("hNotes");const hadithMsg=document.getElementById("hadithMsg");const mSources=document.getElementById("mSources");const mHadiths=document.getElementById("mHadiths");const mReview=document.getElementById("mReview");const mPublished=document.getElementById("mPublished");const recentSources=document.getElementById("recentSources");const sourcesRows=document.getElementById("sourcesRows");const hadithRows=document.getElementById("hadithRows");const reviewRows=document.getElementById("reviewRows");const statusStats=document.getElementById("statusStats");const typeStats=document.getElementById("typeStats");const catalogResults=document.getElementById("catalogResults");const sourceSearch=document.getElementById("sourceSearch");const hadithSearch=document.getElementById("hadithSearch");const hadithStatus=document.getElementById("hadithStatus");const catalogSearch=document.getElementById("catalogSearch");const clearSources=document.getElementById("clearSources");const themeBtn=document.getElementById("themeBtn");const exportBtn=document.getElementById("exportBtn");const quickExport=document.getElementById("quickExport");const modal=document.getElementById("modal");const modalBody=document.getElementById("modalBody");const modalClose=document.getElementById("modalClose");
const narratorForm=document.getElementById("narratorForm");const nName=document.getElementById("nName");const nKunya=document.getElementById("nKunya");const nNisba=document.getElementById("nNisba");const nGeneration=document.getElementById("nGeneration");const nNotes=document.getElementById("nNotes");const narratorMsg=document.getElementById("narratorMsg");const narratorRows=document.getElementById("narratorRows");const narratorSearch=document.getElementById("narratorSearch");const judgmentForm=document.getElementById("judgmentForm");const jHadith=document.getElementById("jHadith");const jScholar=document.getElementById("jScholar");const jText=document.getElementById("jText");const jSource=document.getElementById("jSource");const jLocation=document.getElementById("jLocation");const jNotes=document.getElementById("jNotes");const judgmentMsg=document.getElementById("judgmentMsg");const judgmentRows=document.getElementById("judgmentRows");const judgmentSearch=document.getElementById("judgmentSearch");const variantForm=document.getElementById("variantForm");const vHadith=document.getElementById("vHadith");const vText=document.getElementById("vText");const vSource=document.getElementById("vSource");const vLocation=document.getElementById("vLocation");const vMethod=document.getElementById("vMethod");const vNotes=document.getElementById("vNotes");const variantMsg=document.getElementById("variantMsg");const variantRows=document.getElementById("variantRows");const variantSearch=document.getElementById("variantSearch");const auditRows=document.getElementById("auditRows");const toastEl=document.getElementById("toast");
const KEY="basiraHadith.v2";
// طبقة تخزين مبنية على IndexedDB بدل localStorage: تتسع لعشرات الميجابايتات (وأكثر بكثير من سقف localStorage ~5-10MB)
// لتخزين مجموعات حديثية كاملة (مثل صحيح البخاري كاملًا 7000+ سجل) دون فشل الاستيراد.
const IDB_NAME="basiraHadithDB",IDB_STORE="kv";
function idbOpen(){return new Promise((resolve,reject)=>{const req=indexedDB.open(IDB_NAME,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(IDB_STORE))d.createObjectStore(IDB_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function idbGet(key){return idbOpen().then(d=>new Promise((resolve,reject)=>{const tx=d.transaction(IDB_STORE,"readonly"),store=tx.objectStore(IDB_STORE),req=store.get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}))}
function idbSet(key,value){return idbOpen().then(d=>new Promise((resolve,reject)=>{const tx=d.transaction(IDB_STORE,"readwrite"),store=tx.objectStore(IDB_STORE),req=store.put(value,key);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)}))}
function normalizeDB(x){x=x||{};return{sources:Array.isArray(x.sources)?x.sources:[],hadiths:Array.isArray(x.hadiths)?x.hadiths:[],narrators:Array.isArray(x.narrators)?x.narrators:[],judgments:Array.isArray(x.judgments)?x.judgments:[],variants:Array.isArray(x.variants)?x.variants:[],audit:Array.isArray(x.audit)?x.audit:[],settings:x.settings&&typeof x.settings==="object"?x.settings:{theme:"light"}}}
function defaultDB(){return normalizeDB({})}
let db=defaultDB();
async function initDB(){renderAll();try{let stored=await idbGet(KEY);if(!stored){try{const legacy=JSON.parse(localStorage.getItem(KEY)||"null");if(legacy){stored=legacy;await idbSet(KEY,normalizeDB(legacy));toast("تم ترحيل بياناتك السابقة من التخزين القديم (localStorage) إلى IndexedDB بنجاح.")}}catch(e){}}if(stored)db=normalizeDB(stored)}catch(e){console.error("IndexedDB init failed:",e);toast("تعذر فتح قاعدة البيانات المحلية (IndexedDB). البيانات المعروضة قد تكون فارغة.")}applyTheme();renderAll()}
function save(){renderAll();idbSet(KEY,db).catch(e=>{console.error("IndexedDB save failed:",e);toast("تعذر الحفظ في IndexedDB: "+(e&&e.message?e.message:"خطأ غير معروف")+" — التغييرات ظاهرة الآن لكنها قد لا تُحفظ بعد إغلاق الصفحة.")})}
function audit(action,entityType,entityId,details){db.audit.unshift({id:uid("log"),action,entityType,entityId,details:details||"",at:new Date().toISOString()});db.audit=db.audit.slice(0,500)}function uid(p){return p+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,7)}function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
// تطبيع نصوص عربية للبحث فقط: إزالة التشكيل والتطويل وتوحيد أشكال الألف/الياء/التاء المربوطة/الهمزات على الواو والياء.
// لا يُستخدم هذا التطبيع لتعديل النص المخزَّن أو المعروض؛ يقتصر أثره على مطابقة البحث حتى تعمل الكلمات المكتوبة بلا تشكيل مع النصوص المشكَّلة (مثل نصوص صحيح البخاري ومسلم المستوردة).
function normAr(s){return String(s??"").replace(/[\u0610-\u061A\u064B-\u065F\u06D6-\u06DC\u06DF-\u06E8\u06EA-\u06ED\u0670\u200C\u200D\u0640]/g,"").replace(/[إأآا]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/ؤ/g,"و").replace(/ئ/g,"ي").toLowerCase()}
// مطابقة بحث متعددة الكلمات: كل كلمة يكتبها الباحث (مفصولة بمسافة) يجب أن توجد في النص، بأي ترتيب وفي أي مكان — بدل اشتراط تطابق الجملة كاملة كسلسلة واحدة متتالية.
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
function matchQuery(haystackNorm,qNorm){if(!qNorm)return true;return qNorm.split(/\s+/).filter(Boolean).every(t=>haystackNorm.includes(t))}
// ترقيم صفحات بسيط للجداول الكبيرة (آلاف السجلات بعد استيراد الكتب الستة) لمنع تجميد الصفحة عند عرض كل النتائج دفعة واحدة.
const PAGE_SIZE=50;
function paginate(arr,page,pageSize){const totalPages=Math.max(1,Math.ceil(arr.length/pageSize));const p=Math.min(Math.max(1,page||1),totalPages);return{items:arr.slice((p-1)*pageSize,(p-1)*pageSize+pageSize),page:p,totalPages,total:arr.length}}
function pagerRow(colspan,page,totalPages,total,prevFn,nextFn){if(total<=0||totalPages<=1)return"";return'<tr class="pager-row"><td colspan="'+colspan+'"><div style="display:flex;gap:10px;align-items:center;justify-content:center;padding:10px 0;flex-wrap:wrap"><button class="mini-action" '+(page<=1?"disabled":"")+' onclick="'+prevFn+'">« السابق</button><span>صفحة '+page+' من '+totalPages+' — إجمالي '+total+' نتيجة</span><button class="mini-action" '+(page>=totalPages?"disabled":"")+' onclick="'+nextFn+'">التالي »</button></div></td></tr>'}
function badge(s){const c=s==="منشور"?"published":s==="موثق"?"verified":s==="مراجعة"?"review":"draft";return '<span class="badge '+c+'">'+esc(s)+'</span>'}
// شارة مستقلة لحالة المصدر (لا تُستخدم دالة badge الخاصة بحالة الحديث لتفادي ألوان غير دقيقة)
function sourceBadge(active){return active?'<span class="badge verified">مصدر نشط</span>':'<span class="badge draft">بلا سجلات</span>'}
function go(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("hidden",x.id!==v));document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));renderAll();scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-view]").forEach(x=>x.addEventListener("click",()=>go(x.dataset.view)));
function msg(id,t){const x=document.getElementById(id);x.textContent=t;x.classList.remove("hidden");setTimeout(()=>x.classList.add("hidden"),3500)}
// إشعار عام مستقل عن القسم الحالي، لاستخدامه مع إجراءات الهيدر (الاستيراد، النواة العلمية) التي قد تُطلق من أي صفحة
let toastTimer=null;function toast(t){if(!toastEl)return;toastEl.textContent=t;toastEl.classList.remove("hidden");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.add("hidden"),4000)}
// بحث شامل واحد يغطي كل قواعد البيانات (مصادر، أحاديث، رواة، أحكام، روايات) من أي صفحة، مع زر بحث صريح
const globalSearchInput=document.getElementById("globalSearch"),globalSearchBtn=document.getElementById("globalSearchBtn");
function runGlobalSearch(qRaw){const q=normAr((qRaw||"").trim());if(!q){toast("اكتب كلمة أو أكثر للبحث الشامل.");return}
const srcM=db.sources.filter(s=>matchQuery(normAr(s.book+" "+s.author+" "+s.editor+" "+s.publisher+" "+(s.notes||"")),q));
const hadM=db.hadiths.filter(h=>matchQuery(normAr(h.text+" "+h.narrator+" "+h.chapter+" "+h.keywords+" "+h.number),q));
const narM=db.narrators.filter(n=>matchQuery(normAr(n.name+" "+(n.kunya||"")+" "+(n.nisba||"")),q));
const judM=db.judgments.filter(j=>matchQuery(normAr(j.scholar+" "+j.judgment+" "+j.source),q));
const varM=db.variants.filter(v=>matchQuery(normAr(v.text+" "+v.source+" "+v.method),q));
const total=srcM.length+hadM.length+narM.length+judM.length+varM.length;
const block=(title,items,rowFn)=>items.length?('<h3>'+esc(title)+' ('+items.length+')</h3><div class="table-wrap"><table><tbody>'+items.slice(0,25).map(rowFn).join("")+'</tbody></table></div>'):"";
const html='<h2>🔎 نتائج البحث الشامل عن: «'+esc(qRaw)+'»</h2>'+
(total?'<p class="muted">'+total+' نتيجة إجمالًا (تُعرض أول 25 من كل قسم).</p>':'<p class="muted">لا توجد نتائج مطابقة في أي قسم من المنصة.</p>')+
block("المصادر",srcM,s=>'<tr><td><b>'+esc(s.book)+'</b> — '+esc(s.author||"—")+'</td><td><button class="mini-action" onclick="closeModal();sourceView(\''+s.id+'\')">فتح</button></td></tr>')+
block("الأحاديث",hadM,h=>'<tr><td class="truncate">'+esc(h.text)+'</td><td><button class="mini-action" onclick="closeModal();hadithView(\''+h.id+'\')">فتح</button></td></tr>')+
block("الرواة",narM,n=>'<tr><td>'+esc(n.name)+(n.kunya?" — "+esc(n.kunya):"")+'</td><td><button class="mini-action" onclick="closeModal();go(\'narrators\')">عرض القسم</button></td></tr>')+
block("أحكام العلماء",judM,j=>'<tr><td><b>'+esc(j.scholar)+':</b> <span class="truncate">'+esc(j.judgment)+'</span></td><td><button class="mini-action" onclick="closeModal();go(\'judgments\')">عرض القسم</button></td></tr>')+
block("الروايات",varM,v=>'<tr><td class="truncate">'+esc(v.text)+'</td><td><button class="mini-action" onclick="closeModal();go(\'variants\')">عرض القسم</button></td></tr>');
openModal(html)}
globalSearchBtn?.addEventListener("click",()=>runGlobalSearch(globalSearchInput.value));
globalSearchInput?.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();runGlobalSearch(globalSearchInput.value)}});
function renderNarrators(){const q=normAr(narratorSearch?.value||"");narratorRows.innerHTML=db.narrators.filter(n=>matchQuery(normAr(n.name+" "+(n.kunya||"")+" "+(n.nisba||"")),q)).map(n=>'<tr><td><b>'+esc(n.name)+'</b></td><td>'+esc(n.kunya||"—")+'</td><td>'+esc(n.nisba||"—")+'</td><td>'+esc(n.generation||"—")+'</td><td>'+esc(n.notes||"—")+'</td></tr>').join("")||'<tr><td colspan="5">لا توجد أسماء رواة.</td></tr>'}
let judgmentPage=1;
function renderJudgments(){const q=normAr(judgmentSearch?.value||"");const filtered=db.judgments.filter(j=>matchQuery(normAr(j.scholar+" "+j.judgment+" "+j.source),q));const{items,page,totalPages,total}=paginate(filtered,judgmentPage,PAGE_SIZE);judgmentPage=page;const rows=items.map(j=>{const h=db.hadiths.find(x=>x.id===j.hadithId);return '<tr><td>'+esc(h?.number||"—")+'</td><td>'+esc(j.scholar)+'</td><td>'+esc(j.judgment)+'</td><td>'+esc(j.source||"—")+'</td><td>'+esc(j.location||"—")+'</td></tr>'}).join("")||'<tr><td colspan="5">لا توجد أحكام علمائية مطابقة.</td></tr>';judgmentRows.innerHTML=rows+pagerRow(5,page,totalPages,total,"changeJudgmentPage(-1)","changeJudgmentPage(1)")}
function changeJudgmentPage(d){judgmentPage+=d;renderJudgments()}

function renderVariants(){const q=normAr(variantSearch?.value||"");variantRows.innerHTML=db.variants.filter(v=>matchQuery(normAr(v.text+" "+v.source+" "+v.method),q)).map(v=>{const h=db.hadiths.find(x=>x.id===v.hadithId);return '<tr><td>'+esc(h?.number||"—")+'</td><td class="truncate">'+esc(v.text)+'</td><td>'+esc(v.source||"—")+'</td><td>'+esc(v.location||"—")+'</td><td>'+esc(v.method||"—")+'</td></tr>'}).join("")||'<tr><td colspan="5">لا توجد روايات مرتبطة.</td></tr>'}
function renderAudit(){auditRows.innerHTML=db.audit.slice(0,100).map(x=>'<tr><td>'+esc(new Date(x.at).toLocaleString("ar-LY"))+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.entityType)+'</td><td>'+esc(x.details||"—")+'</td></tr>').join("")||'<tr><td colspan="4">لا يوجد سجل تدقيق بعد.</td></tr>'}
sourceForm.addEventListener("submit",e=>{e.preventDefault();const f=sFile.files[0],s={id:uid("src"),book:sBook.value.trim(),author:sAuthor.value.trim(),type:sType.value,editor:sEditor.value.trim(),edition:sEdition.value.trim(),publisher:sPublisher.value.trim(),year:sYear.value.trim(),isbn:sIsbn.value.trim(),url:sUrl.value.trim(),file:f?.name||"",notes:sNotes.value.trim(),createdAt:new Date().toISOString()};if(!s.book)return;db.sources.unshift(s);audit("إنشاء","مصدر",s.id,s.book);save();e.target.reset();msg("sourceMsg","تم حفظ المصدر. يمكنك الآن ربط الأحاديث به.")});
hadithForm.addEventListener("submit",e=>{e.preventDefault();const h={id:uid("had"),sourceId:hSource.value,number:hNumber.value.trim(),chapter:hChapter.value.trim(),narrator:hNarrator.value.trim(),text:hText.value.trim(),isnad:hIsnad.value.trim(),matn:hMatn.value.trim(),page:hPage.value.trim(),keywords:hKeywords.value.trim(),reference:hReference.value.trim(),notes:hNotes.value.trim(),status:"مراجعة",createdAt:new Date().toISOString(),history:[{status:"مراجعة",at:new Date().toISOString()}]};if(!h.sourceId||!h.text){msg("hadithMsg","اختر المصدر وأدخل النص الأصلي.");return}db.hadiths.unshift(h);audit("إنشاء","حديث",h.id,h.number||"سجل جديد");save();e.target.reset();msg("hadithMsg","حُفظ السجل وأُحيل إلى المراجعة العلمية.")});
function renderAll(){if(window.dbHealth){dbHealth.textContent=`${db.sources.length} مصدر · ${db.hadiths.length} حديث · ${db.narrators.length} راوٍ · تخزين محلي`;}mSources.textContent=db.sources.length;mHadiths.textContent=db.hadiths.length;mReview.textContent=db.hadiths.filter(h=>h.status==="مراجعة").length;mPublished.textContent=db.hadiths.filter(h=>h.status!=="مراجعة").length;renderOptions();renderSources();renderHadiths();renderReview();renderRecent();renderStats();renderCatalog();renderTakhrij();renderNarrators();renderJudgments();renderVariants();renderAudit()}
function hadithOptions(sel,filterEl){if(!sel)return;const cur=sel.value,q=normAr(filterEl?.value||"");const sm=new Map(db.sources.map(x=>[x.id,x.book]));const list=[];for(const h of db.hadiths){if(q&&!matchQuery(normAr((h.number||"")+" "+(sm.get(h.sourceId)||"")+" "+String(h.text||"").slice(0,300)),q))continue;list.push(h);if(list.length>=100)break}if(cur&&!list.some(h=>h.id===cur)){const c=db.hadiths.find(h=>h.id===cur);if(c)list.unshift(c)}sel.innerHTML='<option value="">اختر الحديث *</option>'+list.map(h=>'<option value="'+esc(h.id)+'">'+esc(h.number||"بلا رقم")+' — '+esc(sm.get(h.sourceId)||"مصدر")+' — '+esc(String(h.text||"").slice(0,40))+'</option>').join("");sel.value=list.some(h=>h.id===cur)?cur:""}
function mkHadithFilter(sel){if(!sel||sel.dataset.filtered)return null;const inp=document.createElement("input");inp.id=sel.id+"Filter";inp.placeholder="🔎 ضيّق القائمة: رقم الحديث أو الكتاب أو كلمة من النص (تظهر أول 100 نتيجة)";inp.style.gridColumn="1 / -1";inp.oninput=debounce(()=>hadithOptions(sel,inp),300);sel.parentNode.insertBefore(inp,sel);sel.dataset.filtered="1";return inp}
let jFilter=null,vFilter=null;
function renderOptions(){const v=hSource.value;hadithOptions(window.jHadith,jFilter);hadithOptions(window.vHadith,vFilter);hSource.innerHTML='<option value="">اختر المصدر *</option>'+db.sources.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.book)+(s.author?" — "+esc(s.author):"")+"</option>").join("");if(db.sources.some(s=>s.id===v))hSource.value=v}
function renderRecent(){recentSources.innerHTML=db.sources.slice(0,7).map(s=>{const n=db.hadiths.filter(h=>h.sourceId===s.id).length;return '<tr><td><b>'+esc(s.book)+'</b></td><td>'+esc(s.author||"—")+'</td><td>'+n+'</td><td>'+sourceBadge(n>0)+'</td></tr>'}).join("")||'<tr><td colspan="4">لا توجد مصادر.</td></tr>'}
function renderSources(){const q=normAr(sourceSearch.value||"");sourcesRows.innerHTML=db.sources.filter(s=>matchQuery(normAr(s.book+" "+s.author+" "+s.editor+" "+s.publisher),q)).map(s=>{const n=db.hadiths.filter(h=>h.sourceId===s.id).length;return '<tr><td><b>'+esc(s.book)+'</b><div class="mini">'+esc(s.file||"لا يوجد ملف")+'</div></td><td>'+esc(s.author||"—")+'</td><td>'+esc(s.type)+'</td><td>المحقق: '+esc(s.editor||"—")+'<br>الناشر: '+esc(s.publisher||"—")+'<br>'+esc(s.edition||"")+' '+esc(s.year||"")+'</td><td>'+n+'</td><td><button class="mini-action" onclick="sourceView(\''+s.id+'\')">عرض</button> <button class="mini-action" onclick="removeSource(\''+s.id+'\')">حذف</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد نتائج.</td></tr>'}
let hadithPage=1;
function renderHadiths(){const q=normAr(hadithSearch.value||""),st=hadithStatus.value;const filtered=db.hadiths.filter(h=>{const s=db.sources.find(x=>x.id===h.sourceId);return(!st||h.status===st)&&matchQuery(normAr(h.text+" "+h.narrator+" "+(s?.book||"")+" "+h.number+" "+h.keywords),q)});const{items,page,totalPages,total}=paginate(filtered,hadithPage,PAGE_SIZE);hadithPage=page;const rows=items.map(h=>{const s=db.sources.find(x=>x.id===h.sourceId);const nextBtn=h.status!=="منشور"?'<button class="mini-action" onclick="advance(\''+h.id+'\')">التالي</button> ':'';return '<tr><td>'+esc(h.number||"—")+'</td><td>'+esc(s?.book||"مصدر غير معروف")+'</td><td class="truncate" title="'+esc(h.text)+'">'+esc(h.text)+'</td><td>'+esc(h.narrator||"—")+'</td><td>'+badge(h.status)+'</td><td><button class="mini-action" onclick="hadithView(\''+h.id+'\')">فتح</button> '+nextBtn+'<button class="mini-action" onclick="removeHadith(\''+h.id+'\')">حذف</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد نتائج مطابقة لكلمات البحث. جرّب كلمة واحدة أقصر، أو تحقق من الحالة المختارة في القائمة.</td></tr>';hadithRows.innerHTML=rows+pagerRow(6,page,totalPages,total,"changeHadithPage(-1)","changeHadithPage(1)")}
function changeHadithPage(d){hadithPage+=d;renderHadiths()}

let reviewPage=1;
function renderReview(){const{items,page,totalPages,total}=paginate(db.hadiths,reviewPage,PAGE_SIZE);reviewPage=page;const sm=new Map(db.sources.map(x=>[x.id,x.book]));const rows=items.map(h=>{const last=h.history?.at(-1);return '<tr><td>'+esc(h.id)+'</td><td>'+esc(sm.get(h.sourceId)||"—")+'</td><td class="truncate">'+esc(h.text)+'</td><td>'+badge(h.status)+'</td><td>'+esc(last?.at?new Date(last.at).toLocaleString("ar-LY"):"—")+'</td><td><button class="mini-action" onclick="hadithView(\''+h.id+'\')">مراجعة</button></td></tr>'}).join("")||'<tr><td colspan="6">لا توجد سجلات.</td></tr>';reviewRows.innerHTML=rows+pagerRow(6,page,totalPages,total,"changeReviewPage(-1)","changeReviewPage(1)")}
function changeReviewPage(d){reviewPage+=d;renderReview()}
function renderStats(){const total=db.hadiths.length||1,states=[["مراجعة",db.hadiths.filter(h=>h.status==="مراجعة").length],["موثق",db.hadiths.filter(h=>h.status==="موثق").length],["منشور",db.hadiths.filter(h=>h.status==="منشور").length]];statusStats.innerHTML=states.map(x=>'<div class="bar-row"><div class="bar-label"><span>'+x[0]+'</span><b>'+x[1]+'</b></div><div class="bar"><i style="width:'+Math.round(x[1]/total*100)+'%"></i></div></div>').join("");const types={};db.sources.forEach(s=>types[s.type]=(types[s.type]||0)+1);const mx=Math.max(1,...Object.values(types));typeStats.innerHTML=Object.entries(types).map(x=>'<div class="bar-row"><div class="bar-label"><span>'+esc(x[0])+'</span><b>'+x[1]+'</b></div><div class="bar"><i style="width:'+Math.round(x[1]/mx*100)+'%"></i></div></div>').join("")||'<p class="muted">لا توجد مصادر.</p>'}
const takhrijSearch=document.getElementById("takhrijSearch"),takhrijResults=document.getElementById("takhrijResults");
// تعتمد الآن على قاعدة "الروايات" الفعلية بدل حقل familyId غير الموجود في أي سجل — كانت هذه الوظيفة معطّلة تمامًا سابقًا
function renderTakhrij(){if(!takhrijResults)return;const q=normAr(takhrijSearch?.value||"");const groups=db.hadiths.map(h=>({hadith:h,source:db.sources.find(x=>x.id===h.sourceId),variants:db.variants.filter(v=>v.hadithId===h.id)})).filter(g=>g.variants.length>0).filter(g=>{if(!q)return true;const hay=normAr(g.hadith.number+" "+g.hadith.text+" "+g.hadith.narrator+" "+(g.source?.book||"")+" "+(g.hadith.reference||"")+" "+g.variants.map(v=>v.text+" "+v.source).join(" "));return matchQuery(hay,q)});takhrijResults.innerHTML=groups.map(g=>{const title=g.hadith.text.slice(0,110);const rows=[ '<tr><td>'+esc(g.source?.book||"—")+' (النص الأساس)</td><td>'+esc(g.hadith.number||"—")+'</td><td>'+esc(g.hadith.chapter||"—")+'</td><td>'+esc(g.hadith.narrator||"—")+'</td><td class="truncate">'+esc(g.hadith.text)+'</td></tr>' ].concat(g.variants.map(v=>'<tr><td>'+esc(v.source||"رواية بلا مصدر مذكور")+'</td><td>'+esc(v.location||"—")+'</td><td>—</td><td>—</td><td class="truncate">'+esc(v.text)+'</td></tr>')).join("");return '<article class="catalog-card"><h3>📚 '+esc(title)+(title.length>=110?"…":"")+'</h3><p><b>عدد الروايات المرتبطة:</b> '+g.variants.length+'</p><div class="table-wrap"><table><thead><tr><th>المصدر</th><th>الرقم/الموضع</th><th>الباب</th><th>الراوي</th><th>النص</th></tr></thead><tbody>'+rows+'</tbody></table></div></article>'}).join("")||'<div class="notice">لا توجد روايات مرتبطة مسجلة بعد. أضف رواية من قسم «الروايات» واربطها بحديث ليظهر هنا.</div>'}
function renderCatalog(){const q=normAr(catalogSearch.value||"");const cnt=new Map();db.hadiths.forEach(h=>cnt.set(h.sourceId,(cnt.get(h.sourceId)||0)+1));catalogResults.innerHTML=db.sources.filter(s=>{if(!q)return true;if(matchQuery(normAr(s.book+" "+s.author),q))return true;return db.hadiths.some(h=>h.sourceId===s.id&&matchQuery(normAr(h.text+" "+h.narrator+" "+h.keywords),q))}).map(s=>{return '<article class="catalog-card"><h3>📚 '+esc(s.book)+'</h3><p>المؤلف: '+esc(s.author||"غير مدخل")+'</p><p>النوع: '+esc(s.type)+' · السجلات: '+(cnt.get(s.id)||0)+'</p><p>المحقق: '+esc(s.editor||"—")+' · '+esc(s.publisher||"—")+'</p><button class="mini-action" onclick="sourceView(\''+s.id+'\')">تفاصيل المصدر</button></article>'}).join("")||'<div class="notice">لا توجد نتائج.</div>'}
function sourceView(id){const s=db.sources.find(x=>x.id===id);if(!s)return;const hs=db.hadiths.filter(h=>h.sourceId===id);openModal('<h2>📚 '+esc(s.book)+'</h2><p><b>المؤلف:</b> '+esc(s.author||"—")+'</p><p><b>المحقق:</b> '+esc(s.editor||"—")+'</p><p><b>الطبعة:</b> '+esc(s.edition||"—")+' · <b>الناشر:</b> '+esc(s.publisher||"—")+' · <b>السنة:</b> '+esc(s.year||"—")+'</p><p><b>السجلات المرتبطة:</b> '+hs.length+'</p><p>'+esc(s.notes||"")+'</p>')}
function hadithView(id){const h=db.hadiths.find(x=>x.id===id);if(!h)return;const s=db.sources.find(x=>x.id===h.sourceId);const advanceBtn=h.status!=="منشور"?'<button class="primary" onclick="advance(\''+h.id+'\');closeModal()">اعتماد المرحلة التالية</button>':'';openModal('<h2>📜 الحديث '+esc(h.number||"")+'</h2><p><b>المصدر:</b> '+esc(s?.book||"—")+' · <b>الباب:</b> '+esc(h.chapter||"—")+'</p><div class="quote">'+esc(h.text)+'</div><h3>الإسناد</h3><p>'+esc(h.isnad||"لم يُفصل بعد.")+'</p><h3>المتن</h3><p>'+esc(h.matn||"لم يُفصل بعد.")+'</p><p><b>الراوي:</b> '+esc(h.narrator||"—")+' · <b>الموضع:</b> '+esc(h.page||"—")+'</p><p><b>الكلمات المفتاحية:</b> '+esc(h.keywords||"—")+'</p><div class="notice"><b>الحالة:</b> '+badge(h.status)+'</div><div class="form-actions" style="margin-top:12px">'+advanceBtn+'<button onclick="window.print()">طباعة</button></div>')}
function advance(id){const h=db.hadiths.find(x=>x.id===id);if(!h||h.status==="منشور")return;h.status=h.status==="مراجعة"?"موثق":"منشور";h.history=h.history||[];h.history.push({status:h.status,at:new Date().toISOString()});audit("انتقال حالة","حديث",h.id,h.status);save()}
// حذف مصدر يحذف الآن السجلات اليتيمة المرتبطة به (الأحاديث وأحكامها ورواياتها) بدل تركها معلّقة بلا مصدر
function removeSource(id){const relatedHadiths=db.hadiths.filter(h=>h.sourceId===id);const n=relatedHadiths.length;const text=n?`هذا المصدر مرتبط بـ ${n} سجلًا حديثيًا. سيؤدي الحذف إلى حذف هذه السجلات وأي أحكام أو روايات مرتبطة بها. صدّر نسخة احتياطية أولًا إن أردت الاحتفاظ بها. هل تريد المتابعة؟`:"حذف المصدر؟";if(!confirm(text))return;const ids=relatedHadiths.map(h=>h.id);db.judgments=db.judgments.filter(j=>!ids.includes(j.hadithId));db.variants=db.variants.filter(v=>!ids.includes(v.hadithId));db.hadiths=db.hadiths.filter(h=>h.sourceId!==id);db.sources=db.sources.filter(x=>x.id!==id);audit("حذف","مصدر",id,"حذف مصدر و"+n+" سجلًا مرتبطًا");save()}
// جديد: لم تكن هناك وسيلة لحذف حديث خاطئ الإدخال؛ الحذف هنا يزيل أيضًا أحكامه ورواياته المرتبطة
function removeHadith(id){if(!confirm("سيؤدي حذف هذا الحديث إلى حذف أي أحكام أو روايات مرتبطة به. هل تريد المتابعة؟"))return;db.judgments=db.judgments.filter(j=>j.hadithId!==id);db.variants=db.variants.filter(v=>v.hadithId!==id);db.hadiths=db.hadiths.filter(h=>h.id!==id);audit("حذف","حديث",id,"حذف حديث وربطاته");save()}
function exportDB(){const payload={schema:"basira-hadith",version:"2.0",exportedAt:new Date().toISOString(),...db};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download="basira-hadith-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importDB(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.schema!=="basira-hadith"||!Array.isArray(x.sources)||!Array.isArray(x.hadiths))throw new Error("invalid");db=normalizeDB(x);save();applyTheme();toast("تم استيراد النسخة الاحتياطية والتحقق من بنيتها ("+db.sources.length+" مصدرًا، "+db.hadiths.length+" حديثًا)، وحُفظت في IndexedDB.");}catch(e){toast("تعذر الاستيراد: "+(e&&e.message==="invalid"?"بنية الملف غير متوافقة (schema/sources/hadiths).":"تعذرت قراءة الملف كـ JSON صالح: "+(e&&e.message||e)));}};r.readAsText(file,"utf-8")}
function openModal(html){modalBody.innerHTML=html;modal.classList.remove("hidden")}function closeModal(){modal.classList.add("hidden")}modalClose.onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()}
narratorForm?.addEventListener("submit",e=>{e.preventDefault();const n={id:uid("nar"),name:nName.value.trim(),kunya:nKunya.value.trim(),nisba:nNisba.value.trim(),generation:nGeneration.value.trim(),notes:nNotes.value.trim(),createdAt:new Date().toISOString()};if(!n.name)return;db.narrators.unshift(n);audit("إنشاء","راوٍ",n.id,n.name);save();e.target.reset();msg("narratorMsg","تم حفظ بيانات الراوي.")});
judgmentForm?.addEventListener("submit",e=>{e.preventDefault();const j={id:uid("jud"),hadithId:jHadith.value,scholar:jScholar.value.trim(),judgment:jText.value.trim(),source:jSource.value.trim(),location:jLocation.value.trim(),notes:jNotes.value.trim(),createdAt:new Date().toISOString()};if(!j.hadithId||!j.scholar||!j.judgment){msg("judgmentMsg","أكمل الحديث والعالم ونص الحكم.");return}db.judgments.unshift(j);audit("إضافة حكم","حكم علمائي",j.id,j.scholar);save();e.target.reset();msg("judgmentMsg","تم حفظ الحكم منسوبًا إلى قائله.")});
variantForm?.addEventListener("submit",e=>{e.preventDefault();const v={id:uid("var"),hadithId:vHadith.value,text:vText.value.trim(),source:vSource.value.trim(),location:vLocation.value.trim(),method:vMethod.value.trim(),notes:vNotes.value.trim(),createdAt:new Date().toISOString()};if(!v.hadithId||!v.text){msg("variantMsg","اختر الحديث وأدخل نص الرواية.");return}db.variants.unshift(v);audit("إضافة رواية","رواية",v.id,v.source||"رواية مرتبطة");save();e.target.reset();msg("variantMsg","تم حفظ الرواية دون استبدال النص الأصلي.")});
narratorSearch?.addEventListener("input",renderNarrators);judgmentSearch?.addEventListener("input",debounce(()=>{judgmentPage=1;renderJudgments()},300));variantSearch?.addEventListener("input",renderVariants);
async function loadScientificSeed(){try{const res=await fetch("data/seed-hadith-001.json");if(!res.ok)throw new Error("seed");const x=await res.json();let added=0;const add=(arr,key)=>{(x[key]||[]).forEach(item=>{if(!db[arr].some(v=>v.id===item.id)){db[arr].push(item);added++}})};add("sources","sources");add("hadiths","hadiths");add("narrators","narrators");add("judgments","judgments");add("variants","variants");audit("استيراد نواة علمية","حزمة علمية","seed-001","إضافة المادة العلمية الأولى");save();go("dashboard");toast("تم تحميل النواة العلمية: "+added+" سجلًا جديدًا.")}catch(e){toast("تعذر تحميل النواة العلمية: تأكد من وجود ملف data/seed-hadith-001.json.")}}exportBtn.onclick=exportDB;quickExport.onclick=exportDB;const seedBtn=document.getElementById("seedBtn");if(seedBtn)seedBtn.onclick=loadScientificSeed;const importBtn=document.getElementById("importBtn"),importFile=document.getElementById("importFile");if(importBtn&&importFile){importBtn.onclick=()=>importFile.click();importFile.onchange=()=>{if(importFile.files[0])importDB(importFile.files[0]);importFile.value=""}}sourceSearch.oninput=renderSources;hadithSearch.oninput=debounce(()=>{hadithPage=1;renderHadiths()},300);hadithStatus.onchange=()=>{hadithPage=1;renderHadiths()};catalogSearch.oninput=debounce(renderCatalog,300);takhrijSearch?.addEventListener("input",renderTakhrij);
clearSources.onclick=()=>{if(confirm("سيتم حذف جميع المصادر والأحاديث المحلية. صدّر نسخة احتياطية أولًا.")){db.sources=[];db.hadiths=[];db.judgments=[];db.variants=[];save()}}
themeBtn.onclick=()=>{db.settings.theme=db.settings.theme==="dark"?"light":"dark";applyTheme();save()};function applyTheme(){document.documentElement.dataset.theme=db.settings.theme==="dark"?"dark":""}jFilter=mkHadithFilter(window.jHadith);vFilter=mkHadithFilter(window.vHadith);initDB();
